version: "3.8"

services:
  ipfs:
    container_name: miner-ipfs
    image: ipfs/kubo:release
    ports:
      - "4001:4001" # ipfs swarm - expose if needed/wanted
      # - "5001:5001" # ipfs api - expose if needed/wanted
    #     - "8080:8080" # ipfs gateway - expose if needed/wanted
    environment:
      LIBP2P_FORCE_PNET: 1
      LEADER_IPFS_MULTIADDR: ${LEADER_IPFS_MULTIADDR}
      IPFS_SWARM_KEY_FILE: ${IPFS_SWARM_KEY_FILE:-/data/ipfs/swarm.key}
      IS_LEADER: ${IS_LEADER:-false}
    volumes:
      - ipfs-data:/data/ipfs
      - ./ipfs-start.sh:/usr/local/bin/ipfs-start.sh
      - ./swarm.key:/data/ipfs/swarm.key
    networks:
      - ipfs-network
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "chmod +x /usr/local/bin/ipfs-start.sh && /usr/local/bin/ipfs-start.sh",
      ]
    restart: unless-stopped
    healthcheck:
      interval: 10s

  cluster:
    container_name: miner-cluster
    # image: ipfs/ipfs-cluster:latest
    build:
      context: ./
      dockerfile: Dockerfile.follower
    depends_on:
      ipfs:
        condition: service_healthy
      listener:
        condition: service_healthy
    environment:
      CLUSTER_PEERNAME: ${CLUSTER_PEERNAME:-miner}
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs/tcp/5001
      # CLUSTER_CRDT_TRUSTEDPEERS: "*"
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      LEADER_IPFS_CLUSTER_MULTIADDR: ${LEADER_IPFS_CLUSTER_MULTIADDR}
      # CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      # Open API port (allows ipfs-cluster-ctl usage on host)
      - "127.0.0.1:9094:9094"
      # - "9095:9095" # Cluster IPFS Proxy endpoint
      - "9096:9096" # Cluster swarm endpoint
    volumes:
      - ipfs-cluster-data:/data/ipfs-cluster
      - ./follower-start.sh:/usr/local/bin/follower-start.sh
    entrypoint: ["/bin/sh", "/usr/local/bin/follower-start.sh"]
    networks:
      - ipfs-network
    restart: unless-stopped

  listener:
    container_name: miner-listener
    build:
      context: ./relay/ts
    command: sh -c "npx tsx src/listener.ts ${LISTENER_ARGS}"
    environment:
      LEADER_IPFS_CLUSTER_ID: ${LEADER_IPFS_CLUSTER_ID}
    volumes:
      - ipfs-cluster-data:/data/ipfs-cluster
    networks:
      - ipfs-network
    restart: unless-stopped
    healthcheck:
      test: "curl -f http://localhost:3000/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ipfs-network:

volumes:
  ipfs-data:
  ipfs-cluster-data:
