version: "3.8"

services:
  ipfs-manager:
    build:
      context: ./ipfs-manager
      dockerfile: Dockerfile
    environment:
      - CLUSTER_SECRET=${CLUSTER_SECRET}
      - LEADER_IPFS_MULTIADDR=${LEADER_IPFS_MULTIADDR}
      - LEADER_IPFS_CLUSTER_MULTIADDR=${LEADER_IPFS_CLUSTER_MULTIADDR}
    volumes:
      - ipfs-data:/data/ipfs
      - ipfs-cluster-data:/data/ipfs-cluster
    ports:
      - "5001:5001" # IPFS API
      - "9094:9094" # IPFS Cluster API
      - "3000:3000" # Custom API
    networks:
      - ipfs-network

  listener:
    build:
      context: ./relay/ts
      dockerfile: Dockerfile.listener
    command: sh -c "npx tsx src/listener.ts ${LISTENER_ARGS}" 
    networks:
      - ipfs-network

  inscriber:
    build:
      context: ./relay/ts
      dockerfile: Dockerfile.inscriber
    command: sh -c "npx tsx src/inscriber.ts ${INSCRIBER_ARGS}" 
    volumes:
      - ~/.bittensor:/root/.bittensor
    networks:
      - ipfs-network

networks:
  ipfs-network:

volumes:
  ipfs-data:
  ipfs-cluster-data:
